#-------------------------------
# General Site Settings
title: 학생독립만세
tagline: 슬기로운 취준생활 #태그라인 입력
logo: /images/logo.png
description: 취준생 필독서! 학독만의 직무별 채용 트렌드, 취준생 꿀팁, 강의 정보, 수료생 후기, 등 알찬 정보를 블로그를 통해 만나보세요!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.hakdokman.com" # the base hostname & protocol for your site, e.g. http://example.com
blog-theme: light # By default, Atega theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme)
thumbnail_img: '/images/thumbnail.png' #썸네일 이미지 경로 입력


#-------------------------------
# Author Settings
author:
  name: 학생독립만세
  image: '/images/01.jpg'


#-------------------------------
# Hero Settings
hero:
  hero__title: 성장하는 당신을 응원합니다.
  hero__job: 취준생을 위한 진짜 직무 부트캠프
  hero__description: 취업을 위해 진짜 필요한게 뭘까 고민하면서 만든 교육과정이기에 자신있습니다. 여러분은 열심히 참여만 하시면 됩니다.
  hero__button__text: 미래에 투자하는 새로운 방법, 소득공유 후불제(ISA) 자세히 보기
  hero__button__link: '/about'
  hero__image: '/images/01.jpg'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
mailchimp__title: 중요한 소식 이메일로 받아보기 # Add your Title
mailchimp__text: 학독만의 새로운 소식을 받아보시고 싶다면 이메일 주소를 알려주세요. # Add your description.
mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
mailchimp__button__text: 알려주기 # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: contact@hakdokman.com # Add your email for contant form
  description: 학생독립만세의 교육과정의 제휴 문의 또는 인재 채용 문의는 아래의 양식을 작성해주세요.  # Add a description of your form

# NOTE
# Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Social Links (Footer)
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
- {icon: "ion-logo-facebook", link: "https://www.facebook.com/hakdokman"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/hakdokman/"}
# - {icon: "ion-logo-twitter", link: "https://twitter.com"}
# - {icon: "ion-logo-github", link: "https://github.com"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/channel/UCN3HZHDVT1qVqBSHuijOU7w"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: hakdokman # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Gallery Footer Section
gallery:
  title: Gallery
  images:
    - alt: 'Minimalism'
      url: '/images/06.jpg'
    - alt: 'Minimalism'
      url: '/images/05.jpg'
    - alt: 'Minimalism'
      url: '/images/08.jpg'
    - alt: 'Minimalism'
      url: '/images/03.jpg'
    - alt: 'Minimalism'
      url: '/images/09.jpg'
    - alt: 'Minimalism'
      url: '/images/04.jpg'


#-------------------------------
# Google Analytics
google-analytics: UA-116555560-5 # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
